[package]
name = "advent_of_code"
version = "0.8.0"
authors = ["William George Underwood <42812654+WGUNDERWOOD@users.noreply.github.com>"]
edition = "2021"
default-run = "advent_of_code"
publish = false

[dependencies]
itertools = "0.10.5"
ndarray = "0.15.6"
pico-args = "0.5.0"
